name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: Girish-Anadv-07/test.wiki
        path: test.wiki

    - name: Wiki
      run: |
          git config --global user.name "${{secrets.GIT_USER}}"
          git config --global user.email "${{secrets.GIT_GMAIL}}"
          cd test.wiki 
          rm -rf *
          mv ../*.md .
          git add .
          git commit -m "update"
          git push
          
