name: Update Wiki Files
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Wiki
        run: |
          git clone https://github.com/Girish-Anadv-07/test.git
          cd test 
          rm -rf *.md
          cd ..
          mv ./*.md ./test/
          cd test
          git add .
          git commit -m "update"
          git push
          
          
