name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.name "${{secrets.GIT_USER}}"
          git config --global user.email "${{secrets.GIT_GMAIL}}"
          git clone https://github.com/Girish-Anadv-07/test.git
          git clone https://github.com/Girish-Anadv-07/test.wiki.git
          cd test.wiki 
          cd ../test
          mv ./*.md ../test.wiki/
          cd ../test.wiki
          git add .
          git commit -m "update"
          git push
